# Generated by Django 4.0.4 on 2022-05-25 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID tipo producto')),
                ('nomTipo', models.CharField(max_length=15, verbose_name='Gato Perro Exotico')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='La primary key de productos')),
                ('nomProducto', models.CharField(max_length=20, verbose_name='Nombre del producto')),
                ('valor', models.IntegerField(verbose_name='Valor producto')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción del producto')),
                ('stock', models.IntegerField(null=True, verbose_name='Cantidad de productos')),
                ('imgProducto', models.ImageField(upload_to='productos')),
                ('idTipProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.tipoproducto')),
            ],
        ),
    ]
