# Generated by Django 4.0.4 on 2022-06-05 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo')),
                ('nombreTipo', models.CharField(max_length=10, verbose_name='Admin Cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=300, verbose_name='Descripción del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nomProducto',
            field=models.CharField(max_length=50, verbose_name='Nombre del producto'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut usuarios')),
                ('username', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre de usuario')),
                ('clave', models.CharField(max_length=15, verbose_name='Contraseña')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre Cliente')),
                ('apellido', models.CharField(max_length=15, verbose_name='Apellido Cliente')),
                ('correo', models.CharField(max_length=15, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono Agregar el 9')),
                ('idTipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.tipousuario')),
            ],
        ),
    ]
