# Generated by Django 4.0.4 on 2022-06-06 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False, verbose_name='Id comuna')),
                ('ncomuna', models.CharField(max_length=30, verbose_name='Nombre comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id comuna')),
                ('nregion', models.CharField(max_length=30, verbose_name='Nombre region')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo')),
                ('nombreTipo', models.CharField(max_length=10, verbose_name='Admin Cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=300, verbose_name='Descripción del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nomProducto',
            field=models.CharField(max_length=50, verbose_name='Nombre del producto'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id usuarios')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre Cliente')),
                ('apellido', models.CharField(max_length=15, verbose_name='Apellido Cliente')),
                ('clave', models.CharField(max_length=15, verbose_name='Contraseña')),
                ('correo', models.CharField(max_length=15, verbose_name='Correo')),
                ('idTipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False, verbose_name='id Direccion')),
                ('calle', models.CharField(max_length=30, verbose_name='Calle')),
                ('observacion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Observacion si es Casa dpto etc')),
                ('idComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.comuna')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='idRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.region'),
        ),
    ]
