# Generated by Django 4.0.4 on 2022-06-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_tipousuario_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False, verbose_name='Id comuna')),
                ('ncomuna', models.CharField(max_length=30, verbose_name='Nombre comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id comuna')),
                ('nregion', models.CharField(max_length=30, verbose_name='Nombre region')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False, verbose_name='id Direccion')),
                ('calle', models.CharField(max_length=30, verbose_name='Calle')),
                ('observacion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Observacion si es Casa dpto etc')),
                ('idComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.comuna')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='idRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.region'),
        ),
    ]
