# Generated by Django 4.0.4 on 2022-06-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_alter_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='La primary key de usuarios')),
                ('username', models.CharField(max_length=10, verbose_name='Nombre de usuario')),
                ('clave', models.CharField(max_length=15, verbose_name='Contraseña')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre Cliente')),
                ('apellido', models.CharField(max_length=15, verbose_name='Apellido Cliente')),
                ('correo', models.CharField(max_length=15, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono Agregar el 9')),
            ],
        ),
    ]
