# Generated by Django 4.0.4 on 2022-06-05 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('idtipo_user', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo')),
                ('nomb_tipo', models.CharField(max_length=10, verbose_name='Admin Cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=10, null=True, primary_key=True, serialize=False, verbose_name='Rut usuarios'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idtipo_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inicio.tipouser'),
        ),
    ]
